name: 'SQPackager Action'
description: 'An action to install SQPackager and run some check'
inputs:
  sqpackager-version:
    description: 'The version of sqpackager to use'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    -
      name: Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
           git clone https://github.com/Skarsnik/SkarsnikQtCommon.git
           cd SkarsnikQtCommon/SQPackager
           qmake SQPackager.pro -spec win32-msvc CONFIG+="release no_batch"
           nmake
           cd release/
           windeployqt.exe SQPackager.exe --no-translations --no-system-d3d-compiler --no-opengl --release
           Add-Content $env:GITHUB_PATH "$env:GITHUB_WORKSPACE/SkarsnikQtCommon/SQPackager/release/"
    -
      name: Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
           git clone https://github.com/Skarsnik/SkarsnikQtCommon.git
           sudo apt-get install qt6-base-dev
           cd SkarsnikQtCommon/SQPackager
           qmake6 SQPackager.pro CONFIG+="release"
           make
           make clean
           echo "${GITHUB_WORKSPACE}/SkarsnikQtCommon/SQPackager/" >> $GITHUB_PATH